version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: imlunahey/ticket-genie
    container_name: ticket-genie
    restart: unless-stopped
    env_file: .env

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local

